name: flutter_web_demo
description: App built using Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^4.3.2
  built_value: ^7.0.4
  http: ^0.12.0+3

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.2
  built_value_generator: ^7.0.4
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - icons/left_arrow.png
    - assets/
    - assets/logos/
    - fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

